


[features]
seeds = false
skip-lint = false
[programs.localnet]
deposit = "3zGNcvkZXeJhsxc1tcx2wF9WLCUfoquPJbYNymmbVpb2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lonestardev/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"